-- 코드를 입력하세요
SELECT 
    P.PRODUCT_CODE
    , SUM(O.SALES_AMOUNT)*P.PRICE AS SALES
FROM OFFLINE_SALE AS O
INNER JOIN PRODUCT AS P
ON O.PRODUCT_ID = P.PRODUCT_ID

GROUP BY O.PRODUCT_ID

ORDER BY SALES DESC, PRODUCT_CODE;