-- 코드를 작성해주세요
SELECT F.ID, N.FISH_NAME, F.LENGTH
FROM FISH_INFO AS F
JOIN (
SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LEN
FROM FISH_INFO
WHERE LENGTH IS NOT NULL
GROUP BY FISH_TYPE
) M
ON M.FISH_TYPE = F.FISH_TYPE
AND F.LENGTH = M.MAX_LEN
JOIN FISH_NAME_INFO N
ON N.FISH_TYPE = F.FISH_TYPE
ORDER BY F.ID ASC
